// <auto-generated />
using System;
using Civitas.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Civitas.WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("data");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("hora");

                    b.Property<string>("NomeEntidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_entidade");

                    b.Property<string>("NovosValores")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("novos_valores");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operacao");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValoresAtingidos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("valores_atingidos");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("auditoria");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ConsumoPrevisto")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("consumoprevisto");

                    b.Property<string>("DataEmicao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dataemissao");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("datavencimento");

                    b.Property<int>("IdFornecedor")
                        .HasColumnType("integer")
                        .HasColumnName("idfornecedor");

                    b.Property<int>("IdInstituicao")
                        .HasColumnType("integer")
                        .HasColumnName("idinstituicao");

                    b.Property<int>("IdOrcamento")
                        .HasColumnType("integer")
                        .HasColumnName("idorcamento");

                    b.Property<int>("IdTipoDespesa")
                        .HasColumnType("integer")
                        .HasColumnName("idtipodespesa");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numerodocumento");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<string>("UC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("uc");

                    b.HasKey("Id");

                    b.HasIndex("IdFornecedor");

                    b.HasIndex("IdInstituicao")
                        .IsUnique();

                    b.HasIndex("IdOrcamento");

                    b.HasIndex("IdTipoDespesa");

                    b.HasIndex("IdUsuario");

                    b.ToTable("despesa");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iddocumento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDocumento"));

                    b.Property<byte[]>("Digitalizacao")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("digitalizacao");

                    b.Property<int>("IdFluxo")
                        .HasColumnType("integer")
                        .HasColumnName("idfluxo");

                    b.Property<int>("IdFornecedor")
                        .HasColumnType("integer")
                        .HasColumnName("idfornecedor");

                    b.Property<int>("NumeroDocumento")
                        .HasColumnType("integer")
                        .HasColumnName("numerodocumento");

                    b.HasKey("IdDocumento");

                    b.HasIndex("IdFluxo");

                    b.HasIndex("IdFornecedor");

                    b.ToTable("documento");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Fluxo", b =>
                {
                    b.Property<int>("IdFluxo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idfluxo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFluxo"));

                    b.Property<int>("Consumo")
                        .HasMaxLength(100)
                        .HasColumnType("integer")
                        .HasColumnName("consumo");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<float>("ValorPago")
                        .HasMaxLength(100)
                        .HasColumnType("real")
                        .HasColumnName("valorpago");

                    b.HasKey("IdFluxo");

                    b.ToTable("fluxo");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Fornecedor", b =>
                {
                    b.Property<int>("IdFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idfornecedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFornecedor"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nomefantasia");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("telefone");

                    b.HasKey("IdFornecedor");

                    b.ToTable("fornecedor");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Instituicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("estado");

                    b.Property<int>("IdSecretaria")
                        .HasColumnType("integer")
                        .HasColumnName("idsecretaria");

                    b.Property<int>("IdTipoInstituicao")
                        .HasColumnType("integer")
                        .HasColumnName("idtipoinstituicao");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeRazaoSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nomerazaosocial");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("numero");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("IdSecretaria");

                    b.HasIndex("IdTipoInstituicao");

                    b.ToTable("instituicao");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Orcamento", b =>
                {
                    b.Property<int>("IdOrcamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idorcamento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrcamento"));

                    b.Property<int>("AnoOrcamento")
                        .HasColumnType("integer")
                        .HasColumnName("anoorcamento");

                    b.Property<int>("IdInstituicao")
                        .HasColumnType("integer")
                        .HasColumnName("idinstituicao");

                    b.Property<int>("IdTipoDespesa")
                        .HasColumnType("integer")
                        .HasColumnName("idtipodespesa");

                    b.Property<int?>("InstituicaoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoDespesaId")
                        .HasColumnType("integer");

                    b.Property<double>("ValorOrcamento")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("valororcamento");

                    b.HasKey("IdOrcamento");

                    b.HasIndex("IdInstituicao");

                    b.HasIndex("InstituicaoId");

                    b.HasIndex("TipoDespesaId");

                    b.ToTable("orcamento");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Secretaria", b =>
                {
                    b.Property<int>("IdSecretaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idsecretaria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSecretaria"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeRazaoSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nomerazaosocial");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("IdSecretaria");

                    b.ToTable("secretaria");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.TipoDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdUnidadeMedida")
                        .HasColumnType("integer")
                        .HasColumnName("idunidademedida");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<int>("SolicitaUc")
                        .HasColumnType("integer")
                        .HasColumnName("solicitauc");

                    b.HasKey("Id");

                    b.HasIndex("IdUnidadeMedida");

                    b.ToTable("tipodespesa");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.TipoInstituicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.ToTable("tipoinstituicao");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.UnidadeMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("abreviatura");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.ToTable("unidademedida");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("estado");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("matricula");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("senha");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("tipousuario");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Auditoria", b =>
                {
                    b.HasOne("Civitas.WebAPI.Objects.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Despesa", b =>
                {
                    b.HasOne("Civitas.WebAPI.Objects.Models.Fornecedor", "Fornecedor")
                        .WithMany("Despesas")
                        .HasForeignKey("IdFornecedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Civitas.WebAPI.Objects.Models.Instituicao", "Instituicao")
                        .WithOne("Despesa")
                        .HasForeignKey("Civitas.WebAPI.Objects.Models.Despesa", "IdInstituicao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Civitas.WebAPI.Objects.Models.Orcamento", "Orcamento")
                        .WithMany("Despesas")
                        .HasForeignKey("IdOrcamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Civitas.WebAPI.Objects.Models.TipoDespesa", "TipoDespesa")
                        .WithMany("Despesas")
                        .HasForeignKey("IdTipoDespesa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Civitas.WebAPI.Objects.Models.Usuario", "Usuario")
                        .WithMany("Despesas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("Instituicao");

                    b.Navigation("Orcamento");

                    b.Navigation("TipoDespesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Documento", b =>
                {
                    b.HasOne("Civitas.WebAPI.Objects.Models.Fluxo", "Fluxo")
                        .WithMany("Documentos")
                        .HasForeignKey("IdFluxo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Civitas.WebAPI.Objects.Models.Fornecedor", "Fornecedor")
                        .WithMany("Documentos")
                        .HasForeignKey("IdFornecedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fluxo");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Instituicao", b =>
                {
                    b.HasOne("Civitas.WebAPI.Objects.Models.Secretaria", "Secretaria")
                        .WithMany("Instituicoes")
                        .HasForeignKey("IdSecretaria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Civitas.WebAPI.Objects.Models.TipoInstituicao", "TipoInstituicao")
                        .WithMany("Instituicoes")
                        .HasForeignKey("IdTipoInstituicao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Secretaria");

                    b.Navigation("TipoInstituicao");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Orcamento", b =>
                {
                    b.HasOne("Civitas.WebAPI.Objects.Models.Instituicao", "Instituicao")
                        .WithMany()
                        .HasForeignKey("IdInstituicao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Civitas.WebAPI.Objects.Models.Instituicao", null)
                        .WithMany("Orcamento")
                        .HasForeignKey("InstituicaoId");

                    b.HasOne("Civitas.WebAPI.Objects.Models.TipoDespesa", "TipoDespesa")
                        .WithMany()
                        .HasForeignKey("TipoDespesaId");

                    b.Navigation("Instituicao");

                    b.Navigation("TipoDespesa");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.TipoDespesa", b =>
                {
                    b.HasOne("Civitas.WebAPI.Objects.Models.UnidadeMedida", "UnidadeMedida")
                        .WithMany("TiposDespesas")
                        .HasForeignKey("IdUnidadeMedida")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Fluxo", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Fornecedor", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Instituicao", b =>
                {
                    b.Navigation("Despesa")
                        .IsRequired();

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Orcamento", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Secretaria", b =>
                {
                    b.Navigation("Instituicoes");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.TipoDespesa", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.TipoInstituicao", b =>
                {
                    b.Navigation("Instituicoes");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.UnidadeMedida", b =>
                {
                    b.Navigation("TiposDespesas");
                });

            modelBuilder.Entity("Civitas.WebAPI.Objects.Models.Usuario", b =>
                {
                    b.Navigation("Despesas");
                });
#pragma warning restore 612, 618
        }
    }
}
