CREATE TABLE IF NOT EXISTS token_recuperacao_senha (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id integer NOT NULL,
    token_hash varchar(64) NOT NULL,
    criado_em timestamp with time zone NOT NULL,
    expira_em timestamp with time zone NOT NULL,
    utilizado_em timestamp with time zone NULL,
    CONSTRAINT fk_token_recuperacao_senha_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_token_recuperacao_senha_token_hash
    ON token_recuperacao_senha (token_hash);

CREATE UNIQUE INDEX IF NOT EXISTS ux_token_recuperacao_senha_usuario_ativo
    ON token_recuperacao_senha (usuario_id)
    WHERE utilizado_em IS NULL;
